ALTER TABLE "RestaurantConfig"
ADD COLUMN "storeLatitude" DOUBLE PRECISION,
ADD COLUMN "storeLongitude" DOUBLE PRECISION,
ADD COLUMN "deliveryModes" TEXT[] NOT NULL DEFAULT ARRAY['DELIVERY', 'PICKUP'];

ALTER TABLE "Order"
ADD COLUMN "customerLatitude" DOUBLE PRECISION,
ADD COLUMN "customerLongitude" DOUBLE PRECISION,
ADD COLUMN "deliveryDistanceKm" DECIMAL(10,2),
ADD COLUMN "fulfillmentMode" TEXT NOT NULL DEFAULT 'DELIVERY';
