export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GEOCODE_FAILED: 'GEOCODE_FAILED',
  OUTSIDE_DELIVERY_ZONE: 'OUTSIDE_DELIVERY_ZONE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
};

export const errorResponse = (message, code, details) => ({
  message,
  code,
  details
});
